# Generated by Django 6.1.1 on 2026-09-15 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noise_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(max_length=100)),
                ('findings', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('noise_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='noise_logs.noiselog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
